[profile.default]
solc = "0.8.17"
src = 'src'
out = 'out'
test = "test"
libs = ['lib']
fuzz = { runs = 1_000 }

[profile.ci]
fuzz = { runs = 10_000 }
verbosity = 4

[fmt]
line_length = 120
tab_width = 4
bracket_spacing=false
int_types = "long"
func_attrs_with_params_multiline = false
quote_style = "double"
number_underscore = "thousands"
multiline_func_header = "params_first"
single_line_statement_blocks = 'preserve'
variable_override_spacing = true
wrap_comments = false
ignore = []

[rpc_endpoints]
mainnet = "https://eth.llamarpc.com"
bsc = "https://1rpc.io/bnb"
polygon = "https://polygon.llamarpc.com"
avax = "https://avalanche-evm.publicnode.com"
fantom = "https://1rpc.io/ftm"
arbitrum = "https://1rpc.io/arb"
optimism = "https://1rpc.io/op	"
moonriver = "https://moonriver.public.blastapi.io"
gnosis = "https://rpc.ankr.com/gnosis"