name: PRAutoTest
on:
  pull_request:
    paths:
      - 'src/test/*_exp.sol'
env:
  FOUNDRY_PROFILE: ci
jobs:
  check:
    strategy:
      fail-fast: true
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Run Forge tests
        run: |
          shopt -s nullglob
          changed_files=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }} HEAD)
          for file in $changed_files; do
            if [[ $file == src/test/*_exp.sol ]]; then
              forge test --contracts "$file" -vvv
            fi
          done
        id: test
